---

- name: Copy the PHP configuration file
  ini_file:
    path: '{{ php_fpm_ini_path }}'
    option: '{{ item.option }}'
    section: '{{ item.section }}'
    value: '{{ item.value }}'
    backup: true
  with_items: '{{ php_fpm_ini }}'
  when: php_fpm_ini|length > 0
  notify:
    - restart php-fpm
  tags: [configuration, php, fpm]

- name: Copy the FPM configuration
  ini_file:
    path: '{{ php_fpm_config_path }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    backup: true
  with_items: '{{ php_fpm_config }}'
  when: php_fpm_config|length > 0
  register: copy_fpm_config
  notify:
    - restart php-fpm
  tags: [configuration, php, fpm]
