---

- name: Make sure sury.org repository can be used (Debian)
  apt:
    name: apt-transport-https
    state: present
    update_cache: true
    cache_valid_time: '{{ apt_cache_valid_time }}'

- name: Add apt reporitory key (Debian)
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg

- name: Add DEB repository (Debian)
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    update_cache: true
