---

- name: Add the OS specific varibles
  include_vars: "{{role_path}}/vars/{{ ansible_os_family }}.yml"

- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: debian.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_version|int >= 8

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: pools.yml

- name: Check php-fpm syntax of configuration files
  shell: '{{ php_fpm_binary_name }} -t'
  register: result
  when: php_fpm_pools|length > 0
  changed_when: 'result.rc != 0'
  tags: [configuration, php, fpm]

- name: Start the {{ php_fpm_service_name }} service
  service:
    name: '{{ php_fpm_service_name }}'
    state: started
    enabled: true
  when: php_fpm_pools|length > 0
  tags: [service, php, fpm]
